joint_angles:
    vertical_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #intermediate_pick_pose: [179.0, 17.0, 182.0, 231.0, 0.0, 56.0, 92.0]
    perceive_table: [313.7 , 9.9 , 171.9 , 306.3 , 5.3 , 249.66 , 53.88]
    #intermediate_place_pose_right: [220.6 , 340.0 , 344.8 , 285.5 , 4.6 , 271.9 , 115.1]
    #place_pose_right: [219.9 , 328.3 , 347.2 , 260.1 , 7.1 , 308.7 , 112.2]
    perceive_left_pose: [209.7 , 279.9 , 91.9 , 250.3 , 12.6 , 332.66 , 49.88]
    #intermediate_place_pose_left: [163.2 , 325.5 , 344.7 , 308.3 , 8.1 , 264.6 , 57.9]
    #place_pose_left: [160.9 , 315.3 , 347.2 , 282.1 , 9.9 , 300.7 , 53.2]
    #demo_pose: [215.070602417, 355.983215332, 327.985229492, 278.106719971, 4.49846887589, 354.735626221, 88.8878555298] 
